# Borrar los anterior comandos en AMPL
reset;

# Cargar el modelo
model calendari_NFL.mod;

# Cargar los datos
data calendari_NFL.dat;

# Indicadión a ampl de que se quiere utilizar como solver: CPLEX
option solver cplex;

# Resolver
solve;

# Mostrar los resultados
option display_1col infinity;
option omit_zero_rows 1;
display funcio_objectiu;
display {k in Jornades}: {(i,j,k) in Partits_Jornades} Calendari_Optim[i,j,k];

# Ejecutar Ctrl+R